version: 3

images:
  base_image:
    #name: quay.io/ansible/awx-ee:latest
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: ansible-core<2.18
  ansible_runner:
    package_pip: ansible-runner
  python_interpreter:
    package_system: "python3.12"
    python_path: "/usr/bin/python3.12"
  galaxy:
    roles:
        - src: mk-ansible-roles.check_reboot
        - src: mk-ansible-roles.setup_nfs_server
    collections:
        - name: awx.awx
        - name: azure.azcollection
          version: ">=2.1.0"
        - name: google.cloud
        - name: amazon.aws
        - name: community.aws
        - name: vmware.vmware_rest
        - name: community.vmware
          #version: 3.9.0
        - name: openstack.cloud
          #version: 1.8.0
        - name: kubernetes.core
        - name: kubevirt.core
        - name: ovirt.ovirt
        - name: fedora.linux_system_roles
        - name: ansible.posix
        - name: ansible.utils
        - name: community.general
        - name: community.crypto
        # SAP Community Roles
        - name: community.sap_libs
        - name: community.sap_operations
        - name: community.sap_install
        - name: community.sap_launchpad
        - name: community.sap_infrastructure
  python: requirements.txt
  system:
    - python3.12-devel [platform:rpm compile]
    - openssl [platform:rpm]
    - openssl-devel [platform:rpm compile]
    - libxml2 [platform:rpm]
    - libxml2-devel [platform:rpm compile]
    - git-core [platform:rpm]
    - libcurl-devel [platform:rpm compile]
    - krb5-devel [platform:rpm compile]
    - krb5-workstation [platform:rpm]
    - subversion [platform:rpm]
    - subversion [platform:dpkg]
    - git-lfs [platform:rpm]
    - sshpass [platform:rpm]
    - rsync [platform:rpm]
    - epel-release [platform:rpm]
    - unzip [platform:rpm]
    - podman-remote [platform:rpm]
    - cmake [platform:rpm compile]
    - gcc [platform:rpm compile]
    - gcc-c++ [platform:rpm compile]
    - make [platform:rpm compile]
    - openssl-devel [platform:rpm compile]

options:
  package_manager_path: /usr/bin/dnf

additional_build_steps:
  prepend_base:
    - RUN dnf update -y
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - RUN dnf clean all
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.12 312
