version: 3

images:
  base_image:
    #name: quay.io/ansible/awx-ee:latest
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: ansible-core<2.18
  ansible_runner:
    package_pip: ansible-runner
  python_interpreter:
    package_system: "python3.12"
    python_path: "/usr/bin/python3.12"
  galaxy:
    roles:
        - src: mk-ansible-roles.check_reboot
        - src: mk-ansible-roles.setup_nfs_server
    collections:
        - name: awx.awx
          version: 24.6.1
        - name: azure.azcollection
          version: 3.6.0
        - name: google.cloud
          version: 1.6.0
        - name: amazon.aws
          version: 10.1.0
        - name: community.aws
          version: 10.0.0
        - name: vmware.vmware_rest
          version: 4.8.2
        - name: community.vmware
          version: 3.9.0 # 5.7.1
        - name: openstack.cloud
          version: 1.8.0 # 2.4.1
        - name: kubernetes.core
          version: 6.0.0
        - name: kubevirt.core
          version: 2.2.3
        - name: ovirt.ovirt
          version: 3.2.1
        - name: fedora.linux_system_roles
          version: 1.106.0
        - name: ansible.posix
          version: 2.0.0
        - name: ansible.utils
          version: 6.0.0
        - name: community.general
          version: 11.0.0
        - name: community.crypto
          version: 3.0.0
        # SAP Community Roles
        - name: community.sap_libs
          version: 1.4.2
        - name: community.sap_operations
          version: 1.0.0
        - name: community.sap_install
          version: 1.6.0
        - name: community.sap_launchpad
          version: 1.2.1
        - name: community.sap_infrastructure
          version: 1.1.3

  python: requirements.txt
  system:
    - python3.12-devel [platform:rpm compile]
    - openssl [platform:rpm]
    - openssl-devel [platform:rpm compile]
    - libxml2 [platform:rpm]
    - libxml2-devel [platform:rpm compile]
    - git-core [platform:rpm]
    - libcurl-devel [platform:rpm compile]
    - krb5-devel [platform:rpm compile]
    - krb5-workstation [platform:rpm]
    - subversion [platform:rpm]
    - subversion [platform:dpkg]
    - git-lfs [platform:rpm]
    - sshpass [platform:rpm]
    - rsync [platform:rpm]
    - epel-release [platform:rpm]
    - unzip [platform:rpm]
    - podman-remote [platform:rpm]
    - cmake [platform:rpm compile]
    - gcc [platform:rpm compile]
    - gcc-c++ [platform:rpm compile]
    - make [platform:rpm compile]
    - cmake [platform:rpm compile]
    - clang [platform:rpm compile]
    - openssl-devel [platform:rpm compile]
    # binutils [platform:rpm compile]
    # glibc-devel [platform:rpm compile]
    # pkgconf [platform:rpm compile]
    # pkgconf-pkg-config [platform:rpm compile]
    # pkgconf-m4 [platform:rpm compile]

options:
  package_manager_path: /usr/bin/dnf

additional_build_steps:
  #prepend_builder:
  #  - RUN ln -s /usr/bin/gcc /usr/bin/cc
  prepend_base:
    - RUN dnf update -y
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - RUN dnf clean all
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.12 312
